{% set version = "0.0.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sparsebnutils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sparsebnUtils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sparsebnUtils/sparsebnUtils_{{ version }}.tar.gz
  sha256: 7a03725cebb3a6105248c5a2df6e2a9dc4c55facf382bab438918d3c468337f4

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-nnet
  run:
    - r-base
    - r-matrix
    - r-nnet

test:
  commands:
    - $R -e "library('sparsebnUtils')"           # [not win]
    - "\"%R%\" -e \"library('sparsebnUtils')\""  # [win]

about:
  home: https://github.com/itsrainingdata/sparsebnUtils
  license: GPL (>= 2)
  summary: A set of tools for representing and estimating sparse Bayesian networks from continuous and discrete data, as described in Aragam, Gu, and Zhou (2017) <arXiv:1703.04025>.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sparsebnUtils
# Title: Utilities for Learning Sparse Bayesian Networks
# Version: 0.0.7
# Date: 2019-05-28
# Authors@R: c( person("Bryon", "Aragam", email = "sparsebn@gmail.com", role = c("aut", "cre")), person("Jiaying", "Gu", role = c("aut")) )
# Maintainer: Bryon Aragam <sparsebn@gmail.com>
# Description: A set of tools for representing and estimating sparse Bayesian networks from continuous and discrete data, as described in Aragam, Gu, and Zhou (2017) <arXiv:1703.04025>.
# Depends: R (>= 3.2.3)
# Imports: Matrix, stats, utils, methods, nnet
# Suggests: bnlearn, graph, igraph, network, RCy3, testthat
# URL: https://github.com/itsrainingdata/sparsebnUtils
# BugReports: https://github.com/itsrainingdata/sparsebnUtils/issues
# License: GPL (>= 2)
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-05-29 01:49:15 UTC; Zigmund-2
# Author: Bryon Aragam [aut, cre], Jiaying Gu [aut]
# Repository: CRAN
# Date/Publication: 2019-05-29 08:00:09 UTC
