appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: uwN4YmCtW/e4tKbIwltcoZ3xUJq/lObiAg/DWBWsopwerfipchnCXLrGL/NzDb78z0c8YUKtq/cxHRvDWeYYF5kMT1JivnCGfJXHduX7RTwyx3adguvt8djJxkiabagP+HdBJNqpY2GkNwckd4kBZ8yqV4bbd8Rflx4wwlH9nLfVdW0AaCjrxkNUFG90FcpUyNUBLqOBL/h9uiJkAQt3ICr7HhlIaLsUZYhdJqU1xmNlqXqyIzhohjTziaLKM6uUWghg4OaTFzXYyLpsx3QtFZYt1ey5BisuRg4FgnPI+n0K6kVIJjzpdt8/qyUknyF1kK8+5YpuRzS6VFT8tlLE5zlKa7sf5CqdX+Rl9PMPCOms+P5UB0iL0nJjV83PMhbkFbP+bbg681vzH58IlGFHo37s9BYSV4Lj+RBhw7eGkLoEP7BqW+2L9hCBTbGAFkSQ5ZBCatD/WcanJPGcOziWedrPs246GeLcwnGXKyAjex1LyyL7ERiTvUHz8Ds0KGen6NWsAxSVLkPCysIbJNX1b0Que4DybB0PsMevl61XyRjc+X6wPLddXJzp1zVHTvLB1FL1qYhyxoigk0gRZbLMYtwyPpvQ90NjO0s2L5K9UXwVgI09jRi3WWsqz1rBhJYIGCwyw1jFKcew235/Hv1hmYexD4P8PXZxbaHS3AT27Og=}
